### ISSUE TITLE
Fails when uploading file that contains image within a PDF

### ISSUE THREAD

**Issue by Raju03-git** [adrienjoly/npm-pdfreader#101]
When uploading and processing a PDF that contains image then my backend node service fails. I've tried some work arounds, but the service just fails every time.  Please help me resolve this issue.

pdfreader version - 1.2.9
Node Version - 16.13.0

Used File - [pdfReaderIssue.pdf](https://github.com/adrienjoly/npm-pdfreader/files/7764314/pdfReaderIssue.pdf)

**Comment by adrienjoly** [comment]
In order for us to reproduce and investigate, can you share your PDF file and JS code, please?

**Comment by Raju03-git** [comment]
Please find the JS code & Sample File.

**JS Code** - 
           var buffer = '';
          return new Promise((resolve, reject) => {
              new pdfreader.PdfReader().parseFileItems('sample.pdf', function (err, item) {
                  if (err) {
                      reject(err);
                  } else if (!item) {
                      resolve(buffer);
                  }
                  else if (item.text) buffer += item.text;
              });
          });

**PDF File -**
[pdfReaderIssue.pdf](https://github.com/adrienjoly/npm-pdfreader/files/7768853/pdfReaderIssue.pdf)

**Comment by adrienjoly** [comment]
Thank you!

I'll try to find some time to test this. In the meantime, anybody can feel free to give it a go!

**Comment by adrienjoly** [comment]
To investigate, I've tried parsing that file with the `parse.js` script provided in this repo, after enabling the `debug` mode:

```diff
diff --git a/parse.js b/parse.js
index 02100cb..ab0c9e4 100644
--- a/parse.js
+++ b/parse.js
@@ -2,7 +2,7 @@ var LOG = require("./lib/LOG.js").toggle(false);
 var PdfReader = require("./index.js").PdfReader;
 
 function printRawItems(filename, callback) {
-  new PdfReader().parseFileItems(filename, function (err, item) {
+  new PdfReader({ debug: true }).parseFileItems(filename, function (err, item) {
     if (err) callback(err);
     else if (!item) callback();
     else if (item.file) console.log("file =", item.file.path);
```

=> Here's what I'm getting:

```
$ node parse.js '/Users/adrienjoly/Downloads/pdfReaderIssue.pdf'

printing raw items from file: /Users/adrienjoly/Downloads/pdfReaderIssue.pdf ...
file = /Users/adrienjoly/Downloads/pdfReaderIssue.pdf
Warning: Setting up fake worker.
Warning: Unhandled rejection: ReferenceError: MozBlobBuilder is not defined
ReferenceError: MozBlobBuilder is not defined
    at Object.createBlob (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1104:12)
    at Object.createObjectURL (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1112:24)
    at JpegStream_getIR [as getIR] (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:25575:18)
    at PartialEvaluator_buildPaintImageXObject [as buildPaintImageXObject] (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7120:64)
    at PartialEvaluator_getOperatorList [as getOperatorList] (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7464:24)
    at Object.eval [as onResolve] (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4348:26)
    at Object.runHandlers (eval at <anonymous> (/Users/adrienjoly/dev/adrienjoly/npm-pdfreader/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:864:35)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by adrienjoly** [comment]
After upgrading `pdf2json` to version `2.0.0` in package.json, here's what I'm getting:

```
$ node parse.js '/Users/adrienjoly/Downloads/pdfReaderIssue.pdf'

printing raw items from file: /Users/adrienjoly/Downloads/pdfReaderIssue.pdf ...
file = /Users/adrienjoly/Downloads/pdfReaderIssue.pdf
Warning: Setting up fake worker.
Warning: TT: undefined function: 32
(node:47195) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
page = 1
4.252   14.793          left    29      Sample
6.254   14.793          left    23      check
done.
```

=> If you want to upgrade that dependency in that project, add the following lines in your `package.json` then run `npm install` again:

```
  "resolutions": {
    "pdf2json": "2.0.0"
  }
```
