### ISSUE TITLE
pdfreader.parseFileItems throw error can not catch ?   

### ISSUE THREAD

**Issue by Yi-love** [adrienjoly/npm-pdfreader#14]
pdf url : http://www.hkexnews.hk/listedco/listconews/sehk/2018/0228/LTN20180228058_C.pdf

Error: Required "glyf" or "loca" tables are not found
    at error (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:193:7)
    at Font_checkAndRepair [as checkAndRepair] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:12213:11)
    at new Font (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:10756:21)
    at PartialEvaluator_translateFont [as translateFont] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:8161:14)
    at PartialEvaluator_loadFont [as loadFont] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:7311:29)
    at PartialEvaluator_handleSetFont [as handleSetFont] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:7154:23)
    at PartialEvaluator_getOperatorList [as getOperatorList] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:7470:37)
    at Object.eval [as onResolve] (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:4345:26)
    at Object.runHandlers (eval at <anonymous> (E:\git\9w\node_modules\pdf2json\lib\pdf.js:60:1), <anonymous>:864:35)

**Comment by adrienjoly** [comment]
Hi! This error seems to come from the `pdf2json` dependency => can you look on their repo if you find any solution to this problem?

**Comment by Yi-love** [comment]
you need update the `pdf2json@1.1.7` dependency.

**Comment by adrienjoly** [comment]
Did you successfully test that it works as expected with that version?

If so, feel free to commit that change and submit a Pull Request! :-)

**Comment by adrienjoly** [comment]
Upgrading to `pdf2json@1.1.7` seems risky as they introduced breaking changes since the version that `pdfreader` currently uses (`v0.7`), cf changelog: https://github.com/modesty/pdf2json/releases

The error handling problem that you mention seems to be fixed in `pdf2json@1.0.1`, cf https://github.com/modesty/pdf2json/issues/41.

**Comment by adrienjoly** [comment]
Fixed in https://github.com/adrienjoly/npm-pdfreader/releases/tag/v1.0.0 => Closing.

Thanks again for reporting this bug, Yi! 🙌
